-- ========================================================
-- LIFT App - Supabase Schema Migration Script (Routines, AI Chat, Custom Exercises)
-- Copy and run this script in Supabase Dashboard -> SQL Editor
-- ========================================================

-- 1. Routines Table
CREATE TABLE IF NOT EXISTS public.routines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  is_synced INT DEFAULT 1
);

ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own routines"
  ON public.routines FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 2. Routine Exercises Table
CREATE TABLE IF NOT EXISTS public.routine_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  routine_id BIGINT NOT NULL REFERENCES public.routines(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  order_index INT NOT NULL,
  is_synced INT DEFAULT 1
);

ALTER TABLE public.routine_exercises ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own routine exercises"
  ON public.routine_exercises FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 3. Routine Sets Table
CREATE TABLE IF NOT EXISTS public.routine_sets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  routine_exercise_id BIGINT NOT NULL REFERENCES public.routine_exercises(id) ON DELETE CASCADE,
  set_number INT NOT NULL,
  weight_kg DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  reps INT NOT NULL DEFAULT 10,
  is_warmup BOOLEAN NOT NULL DEFAULT false,
  is_synced INT DEFAULT 1
);

ALTER TABLE public.routine_sets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own routine sets"
  ON public.routine_sets FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 4. AI Chat Messages Table (Optional Cloud Sync for AI Chat)
CREATE TABLE IF NOT EXISTS public.ai_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  is_user BOOLEAN NOT NULL,
  text TEXT NOT NULL,
  timestamp BIGINT NOT NULL
);

ALTER TABLE public.ai_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own AI chat messages"
  ON public.ai_chat_messages FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 5. Custom Exercises Table (Optional Cloud Sync for Custom Exercises)
CREATE TABLE IF NOT EXISTS public.custom_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT,
  created_at BIGINT NOT NULL
);

ALTER TABLE public.custom_exercises ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own custom exercises"
  ON public.custom_exercises FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
